#%Module1.0
module-whatis "scipy"
module-whatis "Version: VERSION"
module-whatis "Description: scipy"
module-whatis "Compiler: ROLLCOMPILER"
module-whatis "Python version: PYVER"
setenv SCIPYHOME /opt/scipy/PYVER
prepend-path PATH /opt/scipy/PYVER/bin
foreach lib [glob -nocomplain /opt/scipy/PYVER/lib*/pythonPYVER/site-packages] {
  prepend-path PYTHONPATH $lib
}
module load ROLLPY llvm

if { [ info exists env(CUDAHOME) ] && [ info exists env(LLVMHOME) ] } {
   set cuda $env(CUDAHOME)
   set llvm $env(LLVMHOME)
   setenv  NUMBAPRO_CUDA_DRIVER  $cuda/lib64/libcudart.so 
   setenv  NUMBAPRO_LIBDEVICE $cuda/nvvm/libdevice
   setenv  NUMBAPRO_NVVM $cuda/nvvm/lib64/libnvvm.so
   setenv  LLVM_CONFIG $llvm/bin/llvm-config
}
