ifndef ROLLPY
  ROLLPY = python
endif

ifndef ROLLPYVERSION
  ROLLPYVERSION = 2.7
endif

NAME           = sdsc-sympy_py$(ROLLPYVERSION)
VERSION        = 1.3
RELEASE        = 0
PKGROOT        = /opt/scipy/$(ROLLPYVERSION)

SRC_SUBDIR     = sympy

SOURCE_NAME    = sympy
SOURCE_SUFFIX  = tar.gz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

MPMATH_NAME    = mpmath
MPMATH_SUFFIX  = tar.gz
MPMATH_VERSION = 1.0.0
MPMATH_PKG     = $(MPMATH_NAME)-$(MPMATH_VERSION).$(MPMATH_SUFFIX)
MPMATH_DIR     = $(MPMATH_PKG:%.$(MPMATH_SUFFIX)=%)


TAR_GZ_PKGS    = $(SOURCE_PKG) $(MPMATH_PKG)

RPM.EXTRAS     = AutoReq:No\nObsoletes: sympy_py$(ROLLPYVERSION)
RPM.PREFIX     = $(PKGROOT)
