ifndef ROLLCOMPILER
  ROLLCOMPILER = gnu
endif
COMPILERNAME := $(firstword $(subst /, ,$(ROLLCOMPILER)))

ifndef ROLLPY
  ROLLPY = python
endif

ifndef ROLLPYVERSION
  ROLLPYVERSION = 2.7
endif

NAME           = sdsc-requests_py$(ROLLPYVERSION)
VERSION        = 2.20.1
RELEASE        = 0
PKGROOT        = /opt/scipy/$(ROLLPYVERSION)

SRC_SUBDIR     = requests

SOURCE_NAME    = requests
SOURCE_SUFFIX  = tar.gz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

URLLIB3_NAME    = urllib3
URLLIB3_SUFFIX  = tar.gz
URLLIB3_VERSION = 1.24.1
URLLIB3_PKG     = $(URLLIB3_NAME)-$(URLLIB3_VERSION).$(URLLIB3_SUFFIX)
URLLIB3_DIR     = $(URLLIB3_PKG:%.$(URLLIB3_SUFFIX)=%)

CERTIFI_NAME    = certifi
CERTIFI_SUFFIX  = tar.gz
CERTIFI_VERSION = 2018.10.15
CERTIFI_PKG     = $(CERTIFI_NAME)-$(CERTIFI_VERSION).$(CERTIFI_SUFFIX)
CERTIFI_DIR     = $(CERTIFI_PKG:%.$(CERTIFI_SUFFIX)=%)

CHARDET_NAME    = chardet
CHARDET_SUFFIX  = tar.gz
CHARDET_VERSION = 3.0.4
CHARDET_PKG     = $(CHARDET_NAME)-$(CHARDET_VERSION).$(CHARDET_SUFFIX)
CHARDET_DIR     = $(CHARDET_PKG:%.$(CHARDET_SUFFIX)=%)
 
IDNA_NAME    = idna
IDNA_SUFFIX  = tar.gz
IDNA_VERSION = 2.7
IDNA_PKG     = $(IDNA_NAME)-$(IDNA_VERSION).$(IDNA_SUFFIX)
IDNA_DIR     = $(IDNA_PKG:%.$(IDNA_SUFFIX)=%)


TAR_GZ_PKGS    = $(SOURCE_PKG) $(URLLIB3_PKG) $(CERTIFI_PKG) $(CHARDET_PKG) $(IDNA_PKG)

RPM.EXTRAS     = AutoReq:No\nObsoletes: requests_py$(ROLLPYVERSION)
RPM.PREFIX     = $(PKGROOT)
